version: "3"

services:
  pg:
    image: postgres:14.4
    environment:
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_USER: 'postgres'
      POSTGRES_DB: 'develop'
    ports:
      - 5432:5432

  pgadmin:
    image: dpage/pgadmin4:6.10
    ports:
      - 3081:80
    environment:
      PGADMIN_DEFAULT_PASSWORD: 'postgres'
      PGADMIN_DEFAULT_EMAIL: 'al.shreyner@gmail.com'
